version: '3.8'
services:
  # server:
  #   build:
  #     context: .
  #     dockerfile: server/Dockerfile
  #   # ports:
  #   #   - "50051:50051"
  #   network_mode: 
  #     "host"

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    # depends_on:
    #   - matchmaking
    network_mode: 
      "host"
    extra_hosts:
    - "matchmaking.local:192.168.49.2"


  # matchmaking:
  #   build:
  #     context: .
  #     dockerfile: matchmaking/Dockerfile
  #   # ports:
  #   #   - "50052:50052"
  #   network_mode: 
  #     "host"

