apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaking
  labels:
    app: matchmaking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchmaking
  template:
    metadata:
      labels:
        app: matchmaking
    spec:
      serviceAccountName: matchmaking-sa
      containers:
      - name: matchmaking
        image: game-backend_matchmaking:latest 
        ports:
        - containerPort: 50052
        command: ["./matchmaking"]