apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - name: grpc_listener
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 8080
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    codec_type: AUTO
                    stat_prefix: grpc
                    http2_protocol_options: {}
                    route_config:
                      name: routes
                      virtual_hosts:
                        - name: game
                          domains: ["*"]
                          routes:
                            # Matchmaking (path-based)
                            - match:
                                prefix: "/server.MatchMakingService/"
                              route:
                                cluster: matchmaking

                            # Game servers (header-based)
                            - match:
                                prefix: "/server.GameService/"
                                headers:
                                  - name: "x-room-id"
                                    safe_regex_match:
                                      google_re2: {}
                                      regex: "game-server-.*"
                              route:
                                cluster: game_servers
                    http_filters:
                    - name: envoy.filters.http.router
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router


      clusters:
        - name: matchmaking
          connect_timeout: 5s
          type: logical_dns
          http2_protocol_options: {}
          load_assignment:
            cluster_name: matchmaking
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: matchmaking.game-backend.svc.cluster.local
                          port_value: 50052

        - name: game_servers
          connect_timeout: 5s
          type: logical_dns
          http2_protocol_options: {}
          load_assignment:
            cluster_name: game_servers
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: game-server-1.game-backend.svc.cluster.local
                          port_value: 7777
