apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matchmaking-ingress
  namespace: game-backend
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  ingressClassName: nginx
  rules:
    - host: matchmaking.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: matchmaking
                port:
                  name: grpc
