apiVersion: v1
kind: Service
metadata:
  name: matchmaking
  namespace: game-backend
spec:
  selector:
    app: matchmaking
  ports:
    - name: grpc
      port: 50052
      targetPort: 50052
  type: ClusterIP