apiVersion: v1
kind: Service
metadata:
  name: matchmaking
  labels:
    app: matchmaking
spec:
  selector:
    app: matchmaking
  ports:
  - name: grpc
    port: 50052
    targetPort: 50052
    protocol: TCP
  type: ClusterIP